# Generated by Django 5.1.2 on 2024-11-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plantcareguide_likes_plantcareguide_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcareguide',
            name='likes',
        ),
        migrations.AddField(
            model_name='plantcareguide',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
