# Generated by Django 5.1.2 on 2024-11-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_savedguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcareguide',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
