# Generated by Django 5.1.2 on 2024-12-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_bio_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcareguide',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
